name: ooi
channels:
  - conda-forge
dependencies:
  - python=3.12
  - argcomplete
  - beautifulsoup4
  - bottleneck
  - cartopy
  - cgsn_parsers
  - cgsn_processing
  - conda-build
  - distributed
  - ephem
  - erddapy
  - flox
  - gsw
  - h5netcdf
  - h5py
  - ipykernel
  - ipympl
  - ioos-qc
  - iris
  - loguru
  - munch
  - nc-time-axis
  - nodejs
  - nose
  - numbagg
  - numexpr
  - opt_einsum
  - packaging
  - pint
  - pip
  - ppigrf
  - pooch
  - pyncml
  - pyco2sys
  - pydap
  - pysolar
  - pyYAML
  - s3fs
  - scikit-learn
  - seaborn
  - sparse
  - sphinx
  - tqdm
  - xarray
  - xlrd
  - zarr
  - pip:
    - canyonbpy
    - https://bitbucket.org/ooicgsn/pyseas/get/develop.zip
